### ISSUE TITLE
Implement objective functions in cpp instead of python, julia, ...?

### ISSUE THREAD

**Issue by bonh** [MeasureTransport/MParT#108]
If most of the map optimization is subject to a similar objective function, e.g., minimization of KL divergence, it might be a good idea to implement this objective function(s) in cpp once instead of implementing it in top-level user code in python or so. 

This is how it looks like in `FromDenisty1D.py` right now:
```
# KL divergence objective
def objective(coeffs, monotoneMap, x, num_points):
    monotoneMap.SetCoeffs(coeffs)
    map_of_x = monotoneMap.Evaluate(x)
    pi_of_map_of_x = rv.logpdf(map_of_x)
    log_det = monotoneMap.LogDeterminant(x)
    return -np.sum(pi_of_map_of_x + log_det)/num_points
```
The `np.sum` might even benefit from direct usage of Eigen vectors, right?

**Comment by dannys4** [comment]
I think I can close this from the PR #304 ?
