### ISSUE TITLE
Fix inverse in matlab bindings

### ISSUE THREAD

**Issue by rubiop** [MeasureTransport/MParT#124]
Inverse method for conditional and triangular map doesn't seem to work properly. Seems to work with value of coefficients set to zeros.

**Comment by rubiop** [comment]
@mparno it doesn't it seems. The error is very weird and close to the issue I had in colab with the `GetBaseFunction()` methods. Here, I got random segmentation error that occurs when I am running the code multiple time in the row, setting the coefficient to full 0s or full 1s seems to be more stable and setting the coefficient multiple times but in a for loop without clearing matlab variables seems to also be more stable. When it doesn't crash the inverse function works perfectly. 

This only occurs with `Inverse()`.

**Comment by mparno** [comment]
@rubiop Can you post a short example with the matlab code that fails?   Thanks!

**Comment by rubiop** [comment]
@mparno Sorry, I think I have found what the issue was. It is because of the `clear all` in top of the file (which is already something bad to use in matlab I think). When replacing it with `clear` things seems to work perfectly
