### ISSUE TITLE
`at` vs `operator[]` functions in `MultiIndexSet` bindings

### ISSUE THREAD

**Issue by michael-c-brennan** [MeasureTransport/MParT#133]
Both functions access `MultiIndex` objects in a `MultiIndexSet`. My main question is if we should have bindings for both functions, and if so, which function should be thought of as the 'standard' way. The main difference is that `at` checks if the index accessed is in bounds for the set, and so it is a bit slower, but it's safer. Average times for me in the python bindings are ~1ms for `operator[]` and ~5ms for `at`. Calling `operator[]` with an out-of-bounds index leads to either a wrong value or a segfault, where `at` reports that the index is out-of-bounds. Given this, I think we should bind `at` to python's `__getitem__ `, to make it the standard way to access indices.

**Comment by mparno** [comment]
Good question @michael-c-brennan !   This is the behavior of `std::vector` in c++, which is why I adopted it for the `MultiIndex`.    In python however, bounds checking with `[]` is the default, so I agree that we should probably map `__getitem__` to the `at` function instead of the `[]` operator.

**Comment by mparno** [comment]
I don't think we need to expose it for now.
