### ISSUE TITLE
Add link to documentation to the right column "About"

### ISSUE THREAD

**Issue by bonh** [MeasureTransport/MParT#136]
For example https://github.com/FEniCS/dolfinx.

**Comment by bonh** [comment]
Just realized that this is not a good example; they link to the project page. But I saw links to readthedocs subpages in other packages...

**Comment by bonh** [comment]
Perhaps it is not as common as I thought?

**Comment by mparno** [comment]
I just added a link to our built documentation on the right side of our main github page.  @bonh Is this what you were intending?
