### ISSUE TITLE
Create extra repository for examples

### ISSUE THREAD

**Issue by bonh** [MeasureTransport/MParT#140]
### Discussed in https://github.com/orgs/MeasureTransport/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **bonh** July 12, 2022</sup>
@mparno suggested in #117 to "create a new repository [...] to hold the examples". Called "maybe something like `MParT-examples`". 

I think this is a good idea, including the name. This would involve to

1. create a new repo, 
2. move the folder [examples](https://github.com/MeasureTransport/MParT/tree/main/examples) into it,
~~3. construct the binder.~~ (will open an extra issue for that once the examples have been moved into the new repo, see #142 )
4. Add a reference to MParT-examples in the README and documentation of MParT.

I would prefer if we would keep the git history while moving the examples into the new repo.
</div>

**Comment by bonh** [comment]
@michael-c-brennan do you like to comment on that? I noticed that you are working on bindings to python which includes changes to example files, see https://github.com/MeasureTransport/MParT/commit/7e7d9a7385729a3ba7613f04c37af4ed9c61b884#diff-b9ed7c5b5a603536f2efa5b104b1aec39cff941d8ad9ee1ed70538ddf7d1cbb3. That means, that if we move the examples into their own repo, the example files won't be present anymore in `MparT` directly. That shouldn't be a problem because you are using `MparT` as a package from your `PYTHONPATH` but still, it would alter your workflow, right?

**Comment by michael-c-brennan** [comment]
@bonh I think having a separate repo for examples is a good idea, and I don't think it would mess with my workflow at all really!
