### ISSUE TITLE
Move matlab binding examples exclusively to `MParT-examples` repo

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#152]
We moved the other examples over, so we should probably stay consistent.

**Comment by rubiop** [comment]
Done (see [commit](https://github.com/MeasureTransport/MParT-examples/commit/b3753e16308958176c44e81b722a72370b38e256))

**Comment by dannys4** [comment]
Just reopening so I can remove them from this repository

**Comment by rubiop** [comment]
completed with #153 #
