### ISSUE TITLE
Overhaul documentation

### ISSUE THREAD

**Issue by mparno** [MeasureTransport/MParT#162]
Make documentation useful for initial JOSS submission.

**Comment by dannys4** [comment]
Some Doc fixes I've been meaning to put up--
- fix minor typo in Tip for powerpc architectures: `add_compile_definitions`, not `add_compile_definition`. 
- Change Julia docs to reflect new stuff (e.g. no `JULIA_EXE`, add `JULIA_INSTALL_PREFIX`)
- Make placeholder path names consistent like `path/to/MParT`
- Mention that Julia might work by just `add`ing from github.
- #188 

I'll add to this as I think of things, probably try to take care of this before the meeting tomorrow.

**Comment by dannys4** [comment]
Also
- [ ] Put Python path stuff into installation section
- [ ] Update Python & Julia examples (maybe up to a CreateComponent and evaluate?)
- [ ] Matlab section for installation and using

**Comment by mparno** [comment]
- [ ] Add descriptions to tutorial table of contents
- [ ] On rendered tutorial pages, add link to corresponding file on github.

**Comment by rubiop** [comment]
@mparno see some ideas in [#36](https://github.com/MeasureTransport/MParT-examples/issues/36)
