### ISSUE TITLE
Figure out how to build docs locally with the tutorials

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#182]
Not sure if this is entirely necessary, but currently, you can't easily do this.

**Comment by bonh** [comment]
You can extract the `.nbconvert.ipynb` from the docker using
```
docker pull quay.io/measuretransport/mpart_examples
container_id=$(docker create quay.io/measuretransport/mpart_examples)
docker cp "$container_id:/home/bayes/examples/python/." ./docs/source/tutorials/.
```
([source](https://unix.stackexchange.com/questions/331645/extract-file-from-docker-image))

or execute the notebooks locally and copy them into `./docs/source/tutorials/.`.

**Comment by bonh** [comment]
If required we could add a routine to make it work with cmake. @mparno implemented something similar already a few commits back.
