### ISSUE TITLE
Document problems with Eigen in conda

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#188]
The `conda-forge` version of Eigen3 is 3.3.7 and, unfortunately, we run into [this issue](https://gitlab.com/libeigen/eigen/-/issues/2290) when compiling with CUDA (or a similar one), which didn't get fixed until 3.3.8 or 9. I could, theoretically, move to bump the version up in conda, but that would likely take more time than it's worth at the moment.

**Comment by mparno** [comment]
Good catch @dannys4 !   I think we should definitely document this version requirement, but I think you can get a newer version on conda-forge as well.  I just tried `conda install -c conda-forge eigen=3.4.0` and it seemed to work for me on my laptop.  I didn't try with any sort of cuda package though, so maybe there is a conflict.

**Comment by dannys4** [comment]
Looks like that works to fix compiling GPU code, at least from my attempt.

**Comment by mparno** [comment]
We now mention the eigen 3.4.0 requirement in the docs.
