### ISSUE TITLE
Add Radial Basis Function parameterization

### ISSUE THREAD

**Issue by mparno** [MeasureTransport/MParT#19]
Create a class that satisfies the [cached parameterization concept](https://measuretransport.github.io/MParT/source/api/concepts/cachedparameterization.html) that implements an expansion of radial basis functions.

**Comment by dannys4** [comment]
some comments on this-- in previous UQ papers, they've used a parameterization from the error function, which is super inefficient. I think we should be using the logit function, which is significantly more efficient. Additionally, we need a way to handle different bandwidth and centers for the RBFs. This can be done in a manner similar to how I handle wavelets in #296 , or it can be done via a method to detect and place RBFs. Previously, they've placed the RBFs according to quantiles of the data distribution, but I think it would be better to use mode-finding on the data (if we're working from samples).

Regardless, if we use this latter path, this is intrinsically related to #338

**Comment by dannys4** [comment]
I'm going to mark this as resolved more-or-less with the introduction of Sigmoids in #346 . While this isn't strictly "RBFs", it *is* equivalent to the idea of integrated RBFs in the triangular transport literature. If we want strict RBFs in the library (perhaps in the context of rectified functions), they can be added as a class and used within the context of the BasisEvaluator concept.
