### ISSUE TITLE
Add `LogDeterminantInputGrad` function to `ConditionalMapBase`

### ISSUE THREAD

**Issue by michael-c-brennan** [MeasureTransport/MParT#230]
To finish the composed map class, we need the ability to compute the gradient w.r.t the input of the Jacobian log-determinant.
Take $T = T_2 \circ T_1$, let $T_1,T_2$ have coefficients $w_1, w_2$. Then
$$\nabla_{w_1} \log |\nabla T(x) | = \nabla_{w_1} \log  |\nabla T_1(x) | + \nabla \log|\nabla T_2(T_1(x))|^\top \nabla_{w_1} T_1(x).$$
and
$$\nabla_{w_2} \log |\nabla T(x) | = \nabla_{w_2} \log  |\nabla T_2(T_1(x)) |.$$

We currently don't have a function for computing $\nabla \log|\nabla T_2(\cdot)|$.

**Comment by dannys4** [comment]
Can we close this?
