### ISSUE TITLE
NVCC Compilation Stalls on `MapFactory.cpp`

### ISSUE THREAD

**Issue by mparno** [MeasureTransport/MParT#231]
The MapFactory class instantiates many different template options and results in VERY long compilation times, especially when compiling with CUDA and NVCC.   Breaking MapFactory.cpp into smaller pieces or explicit instantiated some of the classes in otehr cpp files might help us get around this.

**Comment by dannys4** [comment]
Now that we merged #239 , I think we can close this? I might open up another (lower-priority) issue to refactor the files to make them more readable-- it's hard to tell which file contains what.

The things I would do for partial template instantiation using integers/enums ☹️ .
