### ISSUE TITLE
Create example construction of a Separable Map

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#248]
Have a map with component $j$ of the form
$$T_j(x_1,\dots,x_n) = f(x_1,\dots,x_{j-1}) + u(x_j),$$
for some monotone $u$, or at least $u(x_j) = \int_0^{x_j} g(t)\,dt$ for some $g\geq 0$. We can calculate the derivative of each of these relatively easily (the integral parameterization is particularly trivial). This seems to be something often used in the group, and somewhere we can really gain some speed.

**Comment by mparno** [comment]
Hey @dannys4 !   Unless I'm missing something, I think you could accomplish this right now using the MonotoneComponent class and a MultiindexSet that does not include any cross terms.   If that's the case, then maybe it would be better to add a method for constructing the right multiindex set instead (an alternative to the CreateTotalOrder function).

**Comment by dannys4** [comment]
Hmm... My intent was to make something that's theoretically faster for inverses and derivatives for the diagonal terms, but I'm not sure (barring a class specifically for when the separable term is affine) that would actually speed anything up. Maybe we could make a helper for creating the MultiIndex and then shift this issue into making a short tutorial about it (perhaps that would be a good way of illustrating the power of a MultiIndex).
