### ISSUE TITLE
Insidious bug for `SummarizedMap`

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#268]
@michael-c-brennan found a bug in *somerthing*. I'm not sure what, but I'm increasingly convinced it's in either python or pybind11. It boils down to, when constructing a `SummarizedMap` in Python, the map is made correctly in the constructor, but somehow, its members get overwritten by the time it returns to your python script that `import`s MParT. If you go to the branch dannys4/summarized-component (not to be confused with the original `summarized-component`), you compile with Python, and you execute the script below, you'll see that the `map_` member of SummarizedMap points to something different _within one line of the map getting constructed_.

If you set a watchpoint on the `map_` member, it's clear something changes the value in either Python headers or pybind11 headers. This is infuriating, because I don't think any of us are skilled enough to actually fix this bug.

```python
import mpart as mt
import numpy as np

# problem set up
num_pts = 3
activeInd = 4
noneLim = mt.NoneLim()
opts = mt.MapOptions()

lrc_rank = 2
summary_mat = np.random.randn(lrc_rank, activeInd-1)
summary_fun = mt.AffineFunction(np.asfortranarray(summary_mat))
mset_csemap = mt.MultiIndexSet.CreateTotalOrder(lrc_rank+1, 3, noneLim)
component = mt.CreateComponent(mset_csemap.fix(True), opts)
summarized_component = mt.SummarizedMap(summary_fun, component)
print(summarized_component.print_map_ptr())
```

**Comment by michael-c-brennan** [comment]
This was resolved by changing the private member declarations in `SummarizedMap.h`

Before (worked in c++ programs but python bindings had the problems stated above):
```
private:
 
    std::shared_ptr<ParameterizedFunctionBase<MemorySpace>> const& sumFunc_;
    std::shared_ptr<ConditionalMapBase<MemorySpace>> const& comp_;
```

After (works for both c++ and python bindings):
```
private:
 
    std::shared_ptr<ParameterizedFunctionBase<MemorySpace>> const sumFunc_;
    std::shared_ptr<ConditionalMapBase<MemorySpace>> const comp_;
```
There are a few issues in the pybind11 repo discussing passing variables by reference. I'm assuming this falls under one of those.
