### ISSUE TITLE
`TriangularMap` handing map components without coefficients  (like `IdentityMap`)

### ISSUE THREAD

**Issue by michael-c-brennan** [MeasureTransport/MParT#279]
Something I ran into with `CreateSingleEntryMap`, but can see it affecting other maps in the future. `CreateSingleEntryMap` creates a `TriangularMap` where the top and bottom parts of the map are `IdentityMaps` that sandwich a non-identity component. When I call `CoeffGrad` and `LogDeterminantCoeffGrad`, I just want those methods for the non-identity component, but `TriangularMap` computes these by looping through map components, so I get an error when it hits `assert(false)`, even though that call wasn't going to contribute to the gradient. These loops should skip components without coefficients (e.g. by checking if numCoeffs = 0).

Related to #265

**Comment by dannys4** [comment]
In addition, going down the chain of issues, this is related to #114 and theoretically would get resolved whenever we can get this freeze/thaw stuff implemented.

**Comment by michael-c-brennan** [comment]
Yup! Once freeze/thaw is implemented, we could change the check to be if the component is frozen.
