### ISSUE TITLE
Construct `TriangularMap` with coefficients from its given components

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#282]
Currently, if you invoke the constructor `TriangularMap(std::vector<std::shared_ptr<ConditionalMapBase>> const& components)`, then run `CoeffMap` or something of that ilk, you get an error saying that "the coefficients have not been set", which I don't think should be the case. If you construct a `TriangularMap` from multiple maps you've already made, then they should already have coefficients, no?
Tagging @mparno in case he has thoughts on this.

**Comment by michael-c-brennan** [comment]
The same thing happens with `ComposedMap`, and I totally agree.
