### ISSUE TITLE
Conda-forge feed-stock pull requests are failing

### ISSUE THREAD

**Issue by michael-c-brennan** [MeasureTransport/MParT#342]
MparT feed-stock pull requests for versions 1.4.3, 1.4.4, 2.0.0, 2.0.1 all failed. 

https://github.com/conda-forge/mpart-feedstock/pull/17

**Comment by dannys4** [comment]
I think this is related to https://github.com/MeasureTransport/MParT/issues/326 . I'm unsure how to fix this, and I'll try to get back to this soon.

**Comment by dannys4** [comment]
I'm trying to dig into this and, interestingly, the pull requests started failing between 1.4.0 and 1.4.4 and, if you look at [the changelog](https://github.com/MeasureTransport/MParT/compare/v1.4.0...v1.4.4), that's when we add pip installation. I'm not sure if these are related, but nothing crazy changed about our cmake (except I added cereal and nlopt, which I'm almost certain aren't interfering with the process).

**Comment by lschuler1** [comment]
Hi,
Do you now how to install newer versions then? I'm trying to install the new version by downloading the zip file and the installing it with pip, but I have an error:

**Comment by michael-c-brennan** [comment]
Hi @lschuler1, do you get an error installing with `pip install mpart` (i.e., installing from PyPI, not from the downloaded zip)?

**Comment by lschuler1** [comment]
Yes, it doesn't work either. I am only able to install mpart with conda forge, but in this case it installs the version 1.4
Here is the error I have :


Collecting mpart
  Using cached MParT-2.0.2.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: mpart
  Building wheel for mpart (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  � Building wheel for mpart (pyproject.toml) did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [171 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-build
        Command:
          /tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/u/schuler/.conda/envs/test/bin/python -DPYTHON_INCLUDE_DIR:PATH=/u/schuler/.conda/envs/test/include/python3.11 -DPYTHON_LIBRARY:PATH=/u/schuler/.conda/envs/test/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/u/schuler/.conda/envs/test/bin/python -DPython_ROOT_DIR:PATH=/u/schuler/.conda/envs/test -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/u/schuler/.conda/envs/test/include/python3.11 -DPython3_EXECUTABLE:PATH=/u/schuler/.conda/envs/test/bin/python -DPython3_ROOT_DIR:PATH=/u/schuler/.conda/envs/test -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/u/schuler/.conda/envs/test/include/python3.11 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DKokkos_ENABLE_THREADS:BOOL=ON -DSKBUILD_LIB_RPATH=/u/schuler/.conda/envs/test/lib -DSKBUILD_SITE_PATH=/u/schuler/.conda/envs/test/lib/python3.11/site-packages/ -DPYTHON_INSTALL_SUFFIX=bindings/python/package/ -DMPART_JULIA:BOOL=OFF -DMPART_MATLAB:BOOL=OFF -DMPART_BUILD_TESTS:BOOL=OFF -DMPART_PYTHON:BOOL=ON -DPYTHON_INSTALL_PREFIX= -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 10.2.1
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Will install MParT to /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-install
      -- PYTHON_INSTALL_PREFIX was not set by user, defaulting to /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-install/bindings/python/package/
      -- Python packages will be installed to /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-install/bindings/python/package/
      -- JULIA_INSTALL_PREFIX was not set by user, defaulting to /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-install/julia.
      -- Performing Test COMPILER_IS_NVCC1
      -- Performing Test COMPILER_IS_NVCC1 - Success
      -- Performing Test COMPILER_IS_NVCC2
      -- Performing Test COMPILER_IS_NVCC2 - Failed
      -- Found Kokkos!
      -- MParT is not compiled with CUDA support, so CUBLAS and CUSOLVER will not be used.
      -- Found Eigen:
      -- Could not find pybind11. Fetching source.
      CMake Deprecation Warning at _skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- pybind11 v2.10.0
      CMake Warning (dev) at _skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/tools/pybind11Tools.cmake:50 (find_package)
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/tools/pybind11Common.cmake:180 (include)
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/CMakeLists.txt:200 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /u/schuler/.conda/envs/test/bin/python (found suitable version "3.11.4", minimum required is "3.6")
      -- Found PythonLibs: /u/schuler/.conda/envs/test/lib/libpython3.11.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Could not find Cereal. Fetching source.
      -- Found NLopt: /usr/lib/x86_64-linux-gnu/cmake/nlopt
      -- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen dot
      -- Found Sphinx: /ul/logiciels/SPACK/v0.17/spack/opt/spack/linux-debian11-haswell/gcc-10.2.1/anaconda3-2021.05-hs47cjjrjptwrb4hqrbqpiusvnosry2f/bin/sphinx-build
      SPHINX Executable = /ul/logiciels/SPACK/v0.17/spack/opt/spack/linux-debian11-haswell/gcc-10.2.1/anaconda3-2021.05-hs47cjjrjptwrb4hqrbqpiusvnosry2f/bin/sphinx-build
      CMake Warning at cmake/BuildDocs.cmake:94 (message):
        Could not find jupytext, but this is needed to build the examples when
        MPART_DOCKER_EXAMPLES=OFF.  Will not be able to build tutorial
        documentation.
      Call Stack (most recent call first):
        CMakeLists.txt:366 (Include)
      
      
      -- Configuring done (6.2s)
      CMake Error at CMakeLists.txt:256 (target_link_libraries):
        Target "mpart" links to:
      
          Kokkos::kokkos
      
        but the target was not found.  Possible reasons include:
      
          * There is a typo in the target name.
          * A find_package call is missing for an IMPORTED target.
          * An ALIAS target is missing.
      
      
      
      CMake Error at CMakeLists.txt:322 (target_link_libraries):
        Target "PrintKokkosInfo" links to:
      
          Kokkos::kokkos
      
        but the target was not found.  Possible reasons include:
      
          * There is a typo in the target name.
          * A find_package call is missing for an IMPORTED target.
          * An ALIAS target is missing.
      
      
      
      CMake Error at bindings/python/CMakeLists.txt:37 (target_link_libraries):
        Target "pympart" links to:
      
          Kokkos::kokkos
      
        but the target was not found.  Possible reasons include:
      
          * There is a typo in the target name.
          * A find_package call is missing for an IMPORTED target.
          * An ALIAS target is missing.
      
      
      
      -- Generating done (0.0s)
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 357, in configure
          raise SKBuildError(msg)
      
      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/u/schuler/.conda/envs/test/bin/python -DPYTHON_INCLUDE_DIR:PATH=/u/schuler/.conda/envs/test/include/python3.11 -DPYTHON_LIBRARY:PATH=/u/schuler/.conda/envs/test/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/u/schuler/.conda/envs/test/bin/python -DPython_ROOT_DIR:PATH=/u/schuler/.conda/envs/test -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/u/schuler/.conda/envs/test/include/python3.11 -DPython3_EXECUTABLE:PATH=/u/schuler/.conda/envs/test/bin/python -DPython3_ROOT_DIR:PATH=/u/schuler/.conda/envs/test -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/u/schuler/.conda/envs/test/include/python3.11 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-x9wt6se2/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DKokkos_ENABLE_THREADS:BOOL=ON -DSKBUILD_LIB_RPATH=/u/schuler/.conda/envs/test/lib -DSKBUILD_SITE_PATH=/u/schuler/.conda/envs/test/lib/python3.11/site-packages/ -DPYTHON_INSTALL_SUFFIX=bindings/python/package/ -DMPART_JULIA:BOOL=OFF -DMPART_MATLAB:BOOL=OFF -DMPART_BUILD_TESTS:BOOL=OFF -DMPART_PYTHON:BOOL=ON -DPYTHON_INSTALL_PREFIX= -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1
        Working directory:
          /tmp/pip-install-1lh613cw/mpart_f16e020889244041929b8b27eec137a1/_skbuild/linux-x86_64-3.11/cmake-build
      Please see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpart
Failed to build mpart
ERROR: Could not build wheels for mpart, which is required to install pyproject.toml-based projects

**Comment by dannys4** [comment]
Sorry for the late replies all! I've had some issues recently with my email and didn't get these. @lschuler1 , would you mind trying the conda install again? I fixed it up (coincidentally right after this comment) so it should install 2.1.0

**Comment by dannys4** [comment]
Re: your issue, it looks like you're just using an old version of cmake---I'm guessing it's using whatever your system cmake is, which is fairly outdated. If you check `cmake --version` and it says anything below `3.13`, you'll need to do something like, e.g., `conda install cmake` and that should work out just fine.

**Comment by lschuler1** [comment]
Thank you @dannys4, I just used the conda install and it worked, the new version has been installed

**Comment by dannys4** [comment]
Huzzah! 🎉
