### ISSUE TITLE
Error on creating Triangular Map in MATLAB [v. 2.2.0]

### ISSUE THREAD

**Issue by jgrashorn** [MeasureTransport/MParT#360]
Hey!
I just upgraded to version 2.2.0 of MParT and on calling the `CreateTriangular()`-function I get the following error. Reverting back to version 2.1.0 and using the same code produces no error.
I'm using MATLAB 2023b on Ubuntu.

```Warning: The following error was caught while executing 'ConditionalMap' class destructor:
Error using MParT_
Id is empty.

Error in ConditionalMap/delete (line 92)
    MParT_('ConditionalMap_deleteMap', this.id_);

Error in ConditionalMap (line 26)
    if(nargin==2)

Error in CreateTriangular (line 2)
    map = ConditionalMap(inDim, outDim, order, opts);

Error in Duffing (line 145)
            map{i}(mapIdx) = CreateTriangular(dataSize+mapIdx,1,mapOrder,opts); 
> In ConditionalMap (line 26)
In CreateTriangular (line 2)
In Duffing (line 145) 
Error using MParT_
Option name must be char but is given double.

Error in ConditionalMap (line 81)
      this.id_ = eval(input_str);

Error in CreateTriangular (line 2)
    map = ConditionalMap(inDim, outDim, order, opts);
```

**Comment by dannys4** [comment]
I can replicate this with a simple
```
opts = MapOptions();
trimap = CreateTriangular(2,2,3,opts);
```
(the 2,2,3 are entirely arbitrary). It could be an issue with a recent change; e.g., #353 or honestly even #310.

I'll look into it!

**Comment by dannys4** [comment]
When you get a chance, bump to the latest commit I just put out on `main` and see if your issue is resolved. The tests run on my end, but I'm not sure about you.

**Comment by jgrashorn** [comment]
It works on my end as well, thanks so much!
